=== Ciclo-DAW/LIMA/Tareas/Unidad 4/Tarea 1/pedido.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xsd:schema xmlns:xsd = "http://www.w3.org/2001/XMLSchema" >
  <xsd:annotation>
    <xsd:documentation xml:lang="Es-es">
      Esquema realización de pedidos
      <autor>Brais Cao González</autor>
      <data>2020-05-20</data>
    </xsd:documentation>
  </xsd:annotation>
  <xsd:element name="pedidos" type="pedidoDatos"/>
  <xsd:complexType name="pedidoDatos">
    <xsd:sequence>
      <xsd:element name="pedido" type="pedidoDatos" minOccurs="1" maxOccurs="unbounded" />
    </xsd:sequence>
  </xsd:complexType>
  <xsd:complexType name="pedidoDatos">
    <xsd:sequence>
      <xsd:element name="direccion" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />
      <xsd:element name="traballador" type="xsd:string"/>
      <xsd:element name="data" type="xsd:date" />
      <xsd:element name="observacion" type="xsd:string" minOccurs="0" />
      <xsd:element name="artigo" type="artigoDatos" minOccurs="1" maxOccurs="unbounded" />
    </xsd:sequence>
    <xsd:attribute name="codigo" type="codigoTipo" use="required" />
  </xsd:complexType>
  <xsd:simpleType name="codigoTipo">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="[A-Za-z]([A-Za-z0-9]){7}" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:complexType name="artigoDatos">
    <xsd:sequence>
      <xsd:element name="unidades">
        <xsd:simpleType>
          <xsd:restriction base="xsd:positiveInteger">
            <xsd:minInclusive value="1" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
      <xsd:element name="prezo">
        <xsd:simpleType>
          <xsd:restriction base="xsd:decimal">
           <xsd:minInclusive value="1" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
      <xsd:element name="observacions" type="xsd:string" />
      <xsd:element name="prazo">
        <xsd:simpleType>
          <xsd:restriction base="xsd:positiveInteger">
            <xsd:minInclusive value="1" />
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
    </xsd:sequence>
    <xsd:attribute name="codigo" type="codigoArtigo" use="required" />
  </xsd:complexType>
  <xsd:simpleType name="codigoArtigo">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="[A-Z]{3}-[0-9]{3}" />
    </xsd:restriction>
  </xsd:simpleType>
</xsd:schema>

=== Ciclo-DAW/LIMA/Tareas/Unidad 4/Tarea 1/pedido.xml
<?xml version="1.0" encoding="UTF-8"?>
<pedidos
xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation = "pedido.xsd" >
<pedido codigo="A123A123">
  <direccion>Calle Falsa, N123</direccion>
  <traballador>Brais Cao Gonzalez</traballador>
  <data>2020-05-20</data>
  <observacion>Urxente</observacion>
  <artigo codigo="AAA-000">
    <unidades>1</unidades>
    <prezo>5</prezo>
    <observacions>Entrega en persoa</observacions>
    <prazo>2</prazo>
  </artigo>
   <artigo codigo="AAA-001">
    <unidades>4</unidades>
    <prezo>10</prezo>
    <observacions>Fraxil</observacions>
    <prazo>2</prazo>
  </artigo>
  <artigo codigo="AAA-002">
    <unidades>100</unidades>
    <prezo>7</prezo>
    <observacions>Transportar en horizontal</observacions>
    <prazo>3</prazo>
  </artigo>
</pedido>
<pedido codigo="A999B999">
  <direccion>Calle De la Verdad, N123</direccion>
  <direccion>Calle Unica, N1</direccion>
  <traballador>Paco Perez</traballador>
  <data>2020-04-25</data>
  <artigo codigo="BBB-001">
    <unidades>8</unidades>
    <prezo>500</prezo>
    <observacions>Transportar en vertical</observacions>
    <prazo>1</prazo>
  </artigo>
  <artigo codigo="BBB-002">
    <unidades>200</unidades>
    <prezo>10</prezo>
    <observacions />
    <prazo>10</prazo>
  </artigo>
</pedido>
</pedidos>
